### ISSUE TITLE
update libwacom-surface error

### ISSUE THREAD

**Issue by lonestartexas** [linux-surface/libwacom-surface#10]
I am getting the error "PGP keys need importing:
 -> 594ABBA066118C7A02D10A80A8AF906D9307FBAD, required by: libwacom-surface
:: Import? [Y/n] y
:: Importing keys with gpg...
gpg: keyserver receive failed: No data"
on arch linux.

**Comment by qzed** [comment]
The libwacom devs signed their code with a key that is not present on any of the common key servers. You have 3 options:
- Import the key manually from [Arch Linux libwacom package sources](https://github.com/archlinux/svntogit-packages/blob/packages/libwacom/trunk/keys/pgp/594ABBA066118C7A02D10A80A8AF906D9307FBAD.asc),
- import the key manually from  [the GitHub profile](https://github.com/Joshua-Dickens.gpg) of the developer who released that release,
- or run `makepkg` with `--skippgpcheck` to skip signature verification.

To manually import the key, run `gpg --import <path-to-file>`.

Please do feel free to ask the libwacom devs to push their keys to a keyerver.

**Comment by qzed** [comment]
This should be fixed.
