### ISSUE TITLE
libwacom-bin-surface 2.5.0-1 appears to be missing from https://pkg.surfacelinux.com/debian

### ISSUE THREAD

**Issue by gamer191** [linux-surface/libwacom-surface#11]
I'm not an apt expert, and I can't figure out how to manually check https://pkg.surfacelinux.com/debian, but when I run `sudo apt install libwacom-bin-surface` it gives this output:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libwacom-bin-surface is already the newest version (2.4.0-1).
libwacom-bin-surface set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 4 not to upgrade.
```

(don't worry, I've already run `sudo apt-mark auto libwacom-bin-surface`)

EDIT: in case you're interested, here's the output of `sudo apt update`:

```
Hit:1 https://brave-browser-apt-release.s3.brave.com stable InRelease          
Hit:2 http://archive.canonical.com/ubuntu impish InRelease                     
Hit:3 http://old-releases.ubuntu.com/ubuntu impish InRelease                   
Hit:4 http://old-releases.ubuntu.com/ubuntu impish-updates InRelease        
Hit:5 http://old-releases.ubuntu.com/ubuntu impish-backports InRelease
Hit:6 http://old-releases.ubuntu.com/ubuntu impish-security InRelease
Hit:7 https://pkg.surfacelinux.com/debian release InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

EDIT 2: I reported this because I assume it is as simple as someone forgetting to upload something to the repo. If it is more complicated then that, don't worry, because I'm planning on switching back to Windows soon

**Comment by qzed** [comment]
Thanks for reporting this! I'm not sure why, but the repo system removed the new version instead of the old during cleanup. The libwacom-bin-surface 2.5.0-1 package should be in the package repo now.

**Comment by gamer191** [comment]
> The libwacom-bin-surface 2.5.0-1 package should be in the package repo now.

Indeed it is!
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libwacom-bin-surface is already the newest version (2.5.0-1).
libwacom-bin-surface set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```
Thank you very much for the quick response, and for all your work on `linux-surface`. Have a great day!
