### ISSUE TITLE
Missing Pro 8 support

### ISSUE THREAD

**Issue by YosypC** [linux-surface/libwacom-surface#13]
From [this](https://github.com/linux-surface/linux-surface/discussions/1157#discussioncomment-6136733) discussion, data for the Pro 8 is missing, effectively rendering my Slim Pen 2 useless. Touch screen gestures are also a problem although I am unsure of correct installation, missing packages, or that I am simply dumb. 

```
"libwacom-list-local-devices" output:

/dev/input/event15 is a tablet but not supported by libwacom
/dev/input/event11 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.
```

Knowing how to contribute would be of great help.

**Comment by qzed** [comment]
Can you post the list of devices that shows up when you run `sudo evtest`?
We essentially need the device id and the rest can probably be copied from
the sp7 or spx.

You could also have a look at some other issues where I think I posted some
instructions on how to compile and test (might be on
linux-surface/libwacom). I only have my phone with me right now, but I can
probably post some more detailed instructions later when I'm back home.

**Comment by StollD** [comment]
FYI, the list of devices won't be enough for ITHC devices, you need to input the number of the device and the post this line from the output: 

```
Input device ID: bus 0x0 vendor 0x45e product 0x21 version 0x0
```

Or look at the output of `systemctl status $(iptsd-find-service)` and post the line that says something like

```
[22:13:26.813] [info] Connected to device 045E:0021
```

**Comment by qzed** [comment]
Ah, I somehow thought evtest would contain the ID.

**Comment by StollD** [comment]
Might be a good idea to modify ITHC and add the ID to the name.

**Comment by qzed** [comment]
Or I should just remember to ask for [`scripts/diagnostics.sh`](https://github.com/linux-surface/linux-surface/blob/master/scripts/diagnostics.sh), which should also pick that up.

**Comment by YosypC** [comment]
> Or I should just remember to ask for [`scripts/diagnostics.sh`](https://github.com/linux-surface/linux-surface/blob/master/scripts/diagnostics.sh), which should also pick that up.

@qzed Done! [diagnostics.tar.gz](https://github.com/linux-surface/libwacom-surface/files/11714076/diagnostics.tar.gz)

**Comment by qzed** [comment]
Okay, the device ID is `045E:0C37`.

I've added a branch with the new data file. Can you `git clone https://github.com/linux-surface/libwacom` and `git checkout feature/sp8`, then build and test it by running the following commands?

```
meson setup build
meson compile -C build
./build/libwacom-list-local-devices --database ./data
```

**Comment by quo** [comment]
All touch device IDs for ithc-based Surface devices are documented here: https://github.com/quo/ithc-linux/issues/5

**Comment by qzed** [comment]
@quo neat, thanks!

**Comment by qzed** [comment]
> I've install all the other dependencies and gcc compiler, I can't find this package other than: `Package libgudev-237-4.fc38.x86_64 is already installed.`

You need the development variant since libwacom wants to compile against it and not just use it as runtime-dependencie, i.e. `libgudev-devel` (in general, the libraries you need for developing/compiling applications use the `-devel` suffix).

**Comment by qzed** [comment]
Anyways, this probably will work fine without much testing. Apart from the SP8, we're missing the SP9 and SLS. I'll try to add those as well in a bit and then I'll push an updated package. Feel free to test once I've released that.

**Comment by YosypC** [comment]
I'd be great if I could get a compiled package without installing dependencies one at a time, thanks.

**Comment by qzed** [comment]
@YosypC new packages (v2.7.0-3) should be available ~5 minutes from now.

**Comment by YosypC** [comment]
I have a libwacom setting page now. Thank you.
