### ISSUE TITLE
Can this be added to the [linux-surface] arch linux package repo?

### ISSUE THREAD

**Issue by digitalsignalperson** [linux-surface/libwacom-surface#14]
From https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#arch

> NOTE: libwacom-surface is packaged through the AUR, so you need to install it from there.

I was wondering if the package can be added to https://pkg.surfacelinux.com/arch/

Mainly for convenience in not needing to use AUR in provisioning a linux-surface system.

**Comment by digitalsignalperson** [comment]
Also I'm curious, when are these patches actually needed? I tried replacing libwacom-surface with just libwacom, rebooting, and touch/pen still seems to behave the same (KDE Plasma & wayland, e.g. playing with Xournal++).

**Comment by qzed** [comment]
By having it in AUR, people do not have to add our repo. This is especially useful for older devices, which already have good support out of the box. And I don't really want to maintain two versions of the same package :)

Mostly, this package helps discover some user-space applications to discover the tablet. IIRC Gnome's auto-rotation depended on this.
