### ISSUE TITLE
Dead pre-compiled package link for Debian, Ubuntu release.

### ISSUE THREAD

**Issue by Eraq1** [linux-surface/libwacom-surface#15]
Sorry in-advance as i'm a noob to all this. Trying to install libwacom patch after the surface kernel installation for better touchscreen support but the link for the Debian release is not working. Or am I missing something, thanks.

**Comment by StollD** [comment]
You can either get them from our package repository (https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup) or from the releases on this repo (https://github.com/linux-surface/libwacom-surface/releases/tag/v2.8.0-2).

**Comment by qzed** [comment]
I've removed the outdated instructions and links from the readme.
