### ISSUE TITLE
gnome-control-center crashes with SIGSEGV when accessing Wacom settings

### ISSUE THREAD

**Issue by sughero** [linux-surface/libwacom-surface#16]
I am experiencing a recurring issue with gnome-control-center crashing whenever I try to access the Wacom settings. I am using Arch Linux with the libwacom-surface package installed.

Here are some details about my setup:

- Kernel: Linux surface 6.10.10-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Sun, 15 Sep 2024 02:15:32 +0000 x86_64 GNU/Linux

- Packages:

libwacom-surface version 2.13.0-1
xf86-input-wacom version 1.2.2-1
My input device is recognized as follows:

```shell

$ xinput list
WARNING: running xinput against an Xwayland server. See the xinput man page for details.
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-touch:15                       	id=10	[slave  pointer  (2)]
⎜   ↳ xwayland-tablet stylus:15               	id=11	[slave  pointer  (2)]
⎜   ↳ xwayland-tablet eraser:15               	id=12	[slave  pointer  (2)]
⎜   ↳ xwayland-tablet cursor:15               	id=13	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:15                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:15            	id=7	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer-gestures:15            	id=8	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:15                    	id=9	[slave  keyboard (3)]
``` 

When I attempt to open the Wacom settings in gnome-control-center, I get the following error message:

``` 
fish: Job 1, 'gnome-control-center' terminated by signal SIGSEGV (Address boundary error)
``` 

The journal log shows:

``` 
$ journalctl -xe | grep gnome-control-center

                                                #2  0x000055ceeea7bf35 n/a (gnome-control-center + 0x195f35)
                                                #5  0x000055ceeea77998 cc_wacom_tool_new (gnome-control-center + 0x191998)
                                                #6  0x000055ceeea7be07 n/a (gnome-control-center + 0x195e07)
                                                #33 0x000055ceee948475 main (gnome-control-center + 0x62475)
                                                #36 0x000055ceee948635 _start (gnome-control-center + 0x62635)
ott 13 23:14:18 surface drkonqi-coredump-processor[2594]: "/usr/bin/gnome-control-center" 2546 "/var/lib/systemd/coredump/core.gnome-control-c.1000.2e94868cd6834886b0760a00cee180e8.2546.1728854057000000.zst"
ott 13 23:14:18 surface drkonqi-coredump-launcher[2607]: Unable to find file for pid 2546 expected at "kcrash-metadata/gnome-control-center.2e94868cd6834886b0760a00cee180e8.2546.ini"
ott 13 23:17:01 surface audit[3032]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 pid=3032 comm="gnome-control-c" exe="/usr/bin/gnome-control-center" sig=11 res=1
ott 13 23:17:01 surface kernel: audit: type=1701 audit(1728854221.435:195): auid=1000 uid=1000 gid=1000 ses=4 pid=3032 comm="gnome-control-c" exe="/usr/bin/gnome-control-center" sig=11 res=1
                                                #2  0x00005f9e1d250f35 n/a (gnome-control-center + 0x195f35)
                                                #5  0x00005f9e1d24c998 cc_wacom_tool_new (gnome-control-center + 0x191998)
                                                #6  0x00005f9e1d250e07 n/a (gnome-control-center + 0x195e07)
                                                #31 0x00005f9e1d11d475 main (gnome-control-center + 0x62475)
                                                #34 0x00005f9e1d11d635 _start (gnome-control-center + 0x62635)
ott 13 23:17:02 surface drkonqi-coredump-processor[3094]: "/usr/bin/gnome-control-center" 3032 "/var/lib/systemd/coredump/core.gnome-control-c.1000.2e94868cd6834886b0760a00cee180e8.3032.1728854221000000.zst"
ott 13 23:17:02 surface drkonqi-coredump-launcher[3108]: Unable to find file for pid 3032 expected at "kcrash-metadata/gnome-control-center.2e94868cd6834886b0760a00cee180e8.3032.ini"
$

``` 

It appears to be related to libwacom, as indicated in the logs:

``` 
error in libwacom.so.9.0.0 ...
``` 
I have tried reinstalling xf86-input-wacom, but the issue persists. The Wacom stylus is detected correctly, but the control center crashes when attempting to access its settings.

I would appreciate any assistance or insights regarding this issue.

Thank you!

**Comment by derkrasseleo** [comment]
Does it crash on all settings? For me it only crashes if I click on "assign button"

**Comment by derkrasseleo** [comment]
I opened this issue on the gnome gitlab as well: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/3236

**Comment by sughero** [comment]
Issue Update

I have updated my system, and the kernel is now at version 6.11.4. 

`~> uname -a
Linux surface 6.11.4-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Sun, 20 Oct 2024 14:47:06 +0000 x86_64 GNU/Linux
david@surface ~> 
`
However, I am experiencing crashes with gnome-control-center not only when clicking on the Wacom section but now it crashes regardless of where I click after a certain period of time.
**This is driving me nuts**

@derkrasseleo Which version of kernel are you running?
I should try to play with gnome-control-center on my desktop too to see if the issue shows there too

**Comment by sughero** [comment]
I have a wacom tablet and it works flawlessly on my desktop
This is the image I get typing `gnome-control-center wacom` on a shell on my desktop
![image](https://github.com/user-attachments/assets/d5357b80-39e6-4897-95d3-bd019833123a)
I have no issues.
This is the image I get when I launch `gnome-control-center wacom` on my surface (as you can see pen assignments are missing)
![Screenshot From 2024-10-22 16-14-12](https://github.com/user-attachments/assets/d5261b41-f5f6-4952-ba28-1eb1e5a00b8e)
The pen is 'sort of working' even though isn't customizable in gnome-control-center. You can use it with Xournal++ and it works as a pointer even though it messes up with touchscreen from time to time.
It didn't crash though until a while ago.

**Comment by derkrasseleo** [comment]
I can see the pen settings but when I click on them it crashes on my surface pro 9 with 6.11.4

**Comment by sughero** [comment]
UPDATE
I can't say what happend as I changed so many things and went back everytime because something was not working.
I tried changing kernel flavour from 6.1.x to 6.11.4, changing libwacom-surface, going from wayland to xorg and back, writing some stupid wacom.conf inside /etc/X11/xorg.conf.d/, loading wacom.ko in the kernel (which, who knows why, never loads automatically) and then back with modprobe -r wacom, putting wacom inside initrd and going back removing that module from mkinitcpio.conf. Now, that everything seems back to time 0 this is what I get inside gnome-control-center.
![image](https://github.com/user-attachments/assets/b7b9a762-5778-4f68-97e7-c3ed47abf0ba)
Actually I too get a crash when I dig inside customization button 2 (which does not seem to work as expected!).
Button 1 seems to work even though if I run wayland and  xournal++ it does not what is supposed to do. With X11 it works pretty fine though.
Button 2 is invisible for X11 and Wayland.

**Comment by derkrasseleo** [comment]
If you look at the GNOME issue I opened, they actually fixed it. On arch, I just updated everything and it was fixed.

**Comment by sughero** [comment]
oh geez, they updated gnome-control-center 
avid@surface ~> grep " upgraded gnome-control-center" /var/log/pacman.log |tail -n 5

[2024-06-29T19:48:10+0200] [ALPM] upgraded gnome-control-center (46.2-1 -> 46.3-1)
[2024-08-07T13:31:18+0200] [ALPM] upgraded gnome-control-center (46.3-1 -> 46.4-1)
[2024-09-19T21:36:44+0200] [ALPM] upgraded gnome-control-center (46.4-1 -> 47.0.1-1)
[2024-10-21T22:06:19+0200] [ALPM] upgraded gnome-control-center (47.0.1-1 -> 47.1-1)
[2024-10-23T18:21:46+0200] [ALPM] upgraded gnome-control-center (47.1-1 -> 47.1.1-1)
david@surface ~> 


that's why I see buttons now. I close the issue
