### ISSUE TITLE
Unable to scroll with stylus in firefox

### ISSUE THREAD

**Issue by sayingandparsing** [linux-surface/libwacom-surface#4]
On Arch, I'm running patched firmware from [github.com/dmhacker/arch-linux-surface](github.com/dmhacker/arch-linux-surface), and also installed this package for pen support.
I enabled one finger scrolling on firefox by setting MOZ_USE_XINPUT2=1, which works with a finger but not with the stylus. 
I read that wacom gesture capabilities can interfere with firefox touch screen support, so I tried disabling it with `xsetwacom set "ipts 045E:0020 Pen (0)" Gesture off`, but got the message "Property 'Wacom Enable Touch Gesture' does not exist on device."
Do you have any suggestions on how to proceed?

**Comment by qzed** [comment]
Let me clarify something before I get to the actual issue: The libwacom-surface package is only responsible for identifying touch/pen devices. It doesn't handle any gesture input or input at all. It doesn't really have anything to do with `xinput`/`xf86-input-wacom`. Also it's not a Wacom device, so `xsetwacom`, unless it is some generic command that works for any touchscreen or pen device, will not work. Furthermore, gesture stuff is usually for touchscreen devices and not pen devices, and you're selecting the pen device with the `Pen (0)` suffix.

This brings me to the actual issue at hand: Stylus support (in user-land) in Linux is basically application dependent. What I mean with "basically" is: If the application doesn't choose to implement specific stylus support, DEs usually fall back and convert the stylus input to a plain mouse input and send that to the application instead. This is what you experience here. Usually one would expect the stylus to behave differently than a plain mouse (e.g. scroll the page when dragged), but as Firefox doesn't seem to explicitly handle any stylus input, it just sees the stylus as another mouse and behaves exactly that way. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1606832.

**Comment by sayingandparsing** [comment]
Okay, thanks for the clarification
