### ISSUE TITLE
Doesn't seem to work with the latest Surface Kernel and iptsd

### ISSUE THREAD

**Issue by SamLukeYes** [linux-surface/libwacom-surface#5]
I'm using Arch Linux on Surface Pro 6, with both linux-surface and linux-surface-lts installed.

On the LTS kernel, Wacom settings page looks like this:
![libwacom-surface-4.19.png](https://i.loli.net/2020/07/24/zRvNQLMu6ZCdhmq.png)

On the latest kernel, both the touchscreen and Surface Pen work well with iptsd. However, Wacom settings page doesn't display anything about my devices, and I cannot test my settings on this page either.

![libwacom-surface-5.7.png](https://i.loli.net/2020/07/24/4hBjIZAKbJX6q2x.png)

Tested on GNOME (both Wayland and Xorg).

**Comment by qzed** [comment]
Support for iptsd has been implemented in the latest release.
