### ISSUE TITLE
Surface Book 2 15" - Pen doesn't rotate in Ubuntu 20.04

### ISSUE THREAD

**Issue by forsakenquantum** [linux-surface/libwacom-surface#6]
When I turn a Surface Book 2 15" to portrait mode, the pen input doesn't rotate properly. Touches with my finger on the screen work correctly, but touches with the pen are in the wrong place.

### Environment:
* Hardware model: Surface Book 2 15" with 16 GB RAM, 1 TB HD, and Nvidia 1060 dGPU
* Kernel version: Linux bat 5.9.8-surface #1 SMP Fri Nov 13 21:49:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Distribution: Ubuntu 20.04 focal (Gnome)

Of note is that I had the exact same problem in Linux Mint 20 Cinnamon (with the same kernel) a couple of days ago; I switched to Ubuntu to see if it would fix the problem, but it didn't.

**Comment by qzed** [comment]
Is this still an issue? If so please let me know and I'll reopen it.
