### ISSUE TITLE
Tablet/Stylus visible to CLI but not accessible

### ISSUE THREAD

**Issue by berggggg** [linux-surface/libwacom-surface#8]
Hello devs, and good morning/afternoon/evening.

I've been struggling to get my tablet & stylus to appear in the graphic tablet menu for a few weeks. I (think) have the latest available versions of libwacom-surface and the xf86 driver installed, and while my tablet appears in the terminal with `libwacom-list-local-devices`, its bus is listed as `unknown`, and it does not appear when using `xsetwacom --list devices`, nor does it appear in the graphic tablet menu.

I've searched around as best I can, but I'm kind of at a loss here since there isn't a whole lot of documentation to go around. Any help at all would be appreciated.

System information:
- SB3 13.5" + Surface Pen
- Kubuntu 21.10
- Kernel ver. 5.16.13-surface x86_64
- libwacom-surface ver. 1.12.1-3

`libwacom-list-local-devices` produces the following output:

> devices:
>     - name: 'Microsoft Surface Book 3 (13.5")'
>     - bus: 'unknown'
>     - vid: '0x045e'
>     - pid: '0x09b2'
>     nodes:
>         - /dev/input/event20

If any additional info is needed, I'd be more than happy to oblige. Thanks in advance.

**Comment by Chaos02** [comment]
hey, just FIY I'm having the same issue but your stylus is actually not invisible. It seems like on my Surface Book 1 the stylus pointer seems to be offset to the lower right by pretty much the screen size!
How can we fix this?

**Comment by TheSnowfield** [comment]
I have PR-ed [xf86-input-wacom](https://github.com/linuxwacom/xf86-input-wacom/pull/352) for enabling the libwacom support for IPTS devices.
If you can't wait for the release, add the below section to your `70-wacom.conf`, at the bottom of the file.

For Debian 12 the file is located in  `/usr/share/X11/xorg.conf.d/70-wacom.conf` 

```
# Surface IPTS (Intel Precise Touch and Stylus)
Section "InputClass"
        Identifier "Surface IPTS Device"
        MatchProduct "IPTS"
        MatchDevicePath "/dev/input/event*"
        Driver "wacom"
EndSection
```

![image](https://github.com/user-attachments/assets/39bd1359-8337-48a0-92ce-dadd4bfedc71)

**Comment by qzed** [comment]
@TheSnowfield Thanks for tracking this down and submitting the PR upstream!
